#ifndef INCLUDE_COMPONENTS_TAGS_ANTIDOTECOMPONENT_H_
#define INCLUDE_COMPONENTS_TAGS_ANTIDOTECOMPONENT_H_

#include "ecs/component.h"

class AntidoteComponent : public IComponent {};

#endif  // INCLUDE_COMPONENTS_TAGS_ANTIDOTECOMPONENT_H_
